### ISSUE TITLE
Bug: Error message "An unexpected error has occurred." appears after viewing a project's details and going (back) to 2019's overview

### ISSUE THREAD

**Issue by Zenigame2** [opensummerofcode/edition-webapp#47]
After viewing a project's details (https://osoc.be/2019/<projectname>), going to 2019's overview page (https://osoc.be/2019) would result in the page stating the following: 

> An unexpected error has occurred.

Both using the browser's back functionality as clicking on the "2019" element in the nav-bar while on a project page result in this behaviour.

Error message shows up on Chrome 75.0.3770.142 and Firefox 67.0.2 (64-bit).

**Comment by MichielLeyman** [comment]
Thanks for submitting the issue Alex :)

Fixed in https://github.com/opensummerofcode/edition-webapp/commit/e904689dc81add2a7ebebfddabdc529dd92ff914
