### ISSUE TITLE
Fix edition and GitHub links in footer

### ISSUE THREAD

**Issue by jbelien** [opensummerofcode/edition-webapp#54]
- [x] Current edition : https://github.com/opensummerofcode/edition-webapp/blob/master/components/Common/Footer.jsx#L104
- [x] GitHub link : https://github.com/opensummerofcode/edition-webapp/blob/master/components/Common/Footer.jsx#L174
- [x] Contributors link : https://github.com/opensummerofcode/edition-webapp/blob/master/components/Common/Footer.jsx#L178

**Comment by MichielLeyman** [comment]
Good catch Jonathan, merci bien :)
Done in https://github.com/opensummerofcode/edition-webapp/commit/0d28d953b230fe71a05f7f96e47e43f252c9ab93
