### ISSUE TITLE
On IE 11 it throws "An unexpected error has occurred" when opening any project page

### ISSUE THREAD

**Issue by jeborsel** [opensummerofcode/edition-webapp#61]
example when trying to open https://osoc.be/2019/bebudget on Internet Explorer 11: 
![error_IE11](https://user-images.githubusercontent.com/9434649/62051486-caea8280-b213-11e9-9fe7-51a704a97d27.PNG)

**Comment by jeborsel** [comment]
![errormessage_IE11](https://user-images.githubusercontent.com/9434649/62052299-82cc5f80-b215-11e9-95c8-916448bdd139.PNG)
@MichielLeyman

**Comment by MichielLeyman** [comment]
Fixed in #62. Thanks for reporting Bert :)
